services:
  # Backend service
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: energy-trading-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - GRIDSTATUS_API_KEYS=${GRIDSTATUS_API_KEYS}
    env_file:
      - ./backend/.env
    restart: always
    networks:
      - energy-trading-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend service with optimized build
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev.simple  # Use simple dev dockerfile
    container_name: energy-trading-frontend
    ports:
      - "3000:3000"
    # Mount source for hot reload in development
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Preserve node_modules
      - /app/.next         # Preserve Next.js cache
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - TURBO_TELEMETRY_DISABLED=1
      - BACKEND_URL=http://backend:8000
    restart: always
    networks:
      - energy-trading-network

networks:
  energy-trading-network:
    driver: bridge

volumes:
  backend_data:
    driver: local
  frontend_node_modules:
    driver: local
  frontend_next_cache:
    driver: local