services:
  # Backend service
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: energy-trading-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - GRIDSTATUS_API_KEYS=${GRIDSTATUS_API_KEYS}
    env_file:
      - ./backend/.env
    restart: always
    networks:
      - energy-trading-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend service - optimized for development
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: energy-trading-frontend
    ports:
      - "3000:3000"
    volumes:
      # Mount source for hot reload
      - ./frontend:/app
      # Preserve node_modules and cache for performance
      - /app/node_modules
      - /app/.next
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - TURBO_TELEMETRY_DISABLED=1
      - CHOKIDAR_USEPOLLING=true  # Enable file watching for Docker
      - WATCHPACK_POLLING=true    # Enable webpack polling
      - BACKEND_URL=http://backend:8000
      # Performance optimizations
      - NODE_OPTIONS=--max-old-space-size=2048
    restart: always
    networks:
      - energy-trading-network

# Define custom network for service communication
networks:
  energy-trading-network:
    driver: bridge

# Volumes for persistent data
volumes:
  backend_data:
    driver: local