services:
  # Backend service
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: energy-trading-backend-prod
    ports:
      - "8000:8000"
    environment:
      - GRIDSTATUS_API_KEYS=${GRIDSTATUS_API_KEYS}
    env_file:
      - ./backend/.env
    restart: always
    networks:
      - energy-trading-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend service - Production build
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  # Use production dockerfile
    container_name: energy-trading-frontend-prod
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - BACKEND_URL=http://backend:8000
    restart: always
    networks:
      - energy-trading-network

networks:
  energy-trading-network:
    driver: bridge

volumes:
  backend_data:
    driver: local